#!/usr/bin/env bash
# Bootstrap `.env.deploy` on the NAS.
#
# Usage:
#   scripts/setup/init-env-deploy.sh [--dry-run]
#
# Refuses to overwrite an existing .env.deploy. Pulls POSTGRES_PASSWORD
# from .env.prod instead of duplicating the value. Generates a fresh
# GITHUB_WEBHOOK_SECRET via openssl. Prints the secret at the end with
# the GitHub Settings → Webhooks paste instructions; the operator
# should NOT re-run this script casually because the webhook secret is
# regenerated each time.

set -euo pipefail

cd "$(dirname "$0")/../.."

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      sed -n '1,30p' "$0" | tail -20
      exit 0 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

log() { printf '[init-env-deploy] %s\n' "$*"; }

# --- refuse to overwrite --------------------------------------------------
if [[ -e .env.deploy ]] && [[ "$DRY_RUN" -eq 0 ]]; then
  echo "[init-env-deploy] .env.deploy already exists — refusing to overwrite." >&2
  echo "[init-env-deploy] move/rename it first if you really want to regenerate." >&2
  exit 3
fi

# --- read shared secret from .env.prod -----------------------------------
if [[ ! -f .env.prod ]]; then
  echo "[init-env-deploy] .env.prod not found — create it first from .env.prod.example" >&2
  exit 4
fi
POSTGRES_PW=$(grep -E '^POSTGRES_PASSWORD=' .env.prod | cut -d'=' -f2- | head -n1 || true)
if [[ -z "$POSTGRES_PW" ]]; then
  echo "[init-env-deploy] POSTGRES_PASSWORD missing from .env.prod — add it first" >&2
  exit 5
fi

# --- generate webhook secret --------------------------------------------
WEBHOOK_SECRET=$(openssl rand -hex 32)

# --- compose target file -------------------------------------------------
CONTENTS=$(cat <<EOF
# Generated by scripts/setup/init-env-deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# chmod 0600 admin:users on the NAS. DO NOT commit.

GITHUB_WEBHOOK_SECRET=$WEBHOOK_SECRET
DEPLOY_BRANCH_ALLOWLIST=main
WEBHOOK_SSH_DIR=/volume1/secrets/qufox-ssh
WEBHOOK_PORT=9000
REPO_PATH=/volume2/dockers/qufox
SLACK_WEBHOOK_URL=
BACKUP_DIR=/volume3/qufox-data/backups/qufox
BACKUP_DAILY_KEEP=14
BACKUP_WEEKLY_KEEP=8
BACKUP_CRON='30 3 * * *'
RESTORE_TEST_CRON='45 4 * * 0'
IMAGE_HISTORY_KEEP=10
EOF
)

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "--dry-run: would write the following to .env.deploy (NOT writing):"
  echo "-----"
  echo "$CONTENTS"
  echo "-----"
  log "webhook secret that would be generated (dry-run only, NOT persisted):"
  echo "  $WEBHOOK_SECRET"
  log "POSTGRES_PASSWORD inherited from .env.prod: (hidden, $(printf '%s' "$POSTGRES_PW" | wc -c) chars)"
  exit 0
fi

umask 077
printf '%s\n' "$CONTENTS" > .env.deploy
chmod 0600 .env.deploy
log "wrote .env.deploy (0600, $(stat -c %U:%G .env.deploy 2>/dev/null || echo 'user:group unknown'))"

echo
echo "╭──────────────────────────────────────────────────────────────╮"
echo "│  GITHUB WEBHOOK SECRET — paste into GitHub                   │"
echo "│                                                              │"
echo "│  Repo → Settings → Webhooks → Add webhook (or Edit existing) │"
echo "│                                                              │"
echo "│  Payload URL:   https://deploy.qufox.com/hooks/github        │"
echo "│  Content type:  application/json                             │"
echo "│  Secret:        (paste the value below)                      │"
echo "│  Events:        Just the push event                          │"
echo "│                                                              │"
echo "╰──────────────────────────────────────────────────────────────╯"
echo
echo "  $WEBHOOK_SECRET"
echo
echo "This value is ONLY printed once. Copy it now."
echo "Next: scripts/setup/apply-nginx-diff.sh && scripts/setup/post-switchover-smoke.sh"
