export enum ErrorCode {
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EMAIL_TAKEN = 'AUTH_EMAIL_TAKEN',
  AUTH_USERNAME_TAKEN = 'AUTH_USERNAME_TAKEN',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_SESSION_COMPROMISED = 'AUTH_SESSION_COMPROMISED',

  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_NOT_MEMBER = 'WORKSPACE_NOT_MEMBER',
  WORKSPACE_SLUG_TAKEN = 'WORKSPACE_SLUG_TAKEN',
  WORKSPACE_SLUG_RESERVED = 'WORKSPACE_SLUG_RESERVED',
  WORKSPACE_INSUFFICIENT_ROLE = 'WORKSPACE_INSUFFICIENT_ROLE',
  WORKSPACE_CANNOT_DEMOTE_OWNER = 'WORKSPACE_CANNOT_DEMOTE_OWNER',
  WORKSPACE_CANNOT_REMOVE_OWNER = 'WORKSPACE_CANNOT_REMOVE_OWNER',
  WORKSPACE_OWNER_MUST_TRANSFER = 'WORKSPACE_OWNER_MUST_TRANSFER',
  WORKSPACE_TARGET_NOT_MEMBER = 'WORKSPACE_TARGET_NOT_MEMBER',
  WORKSPACE_ALREADY_MEMBER = 'WORKSPACE_ALREADY_MEMBER',
  WORKSPACE_PURGED = 'WORKSPACE_PURGED',
  WORKSPACE_NOT_PUBLIC = 'WORKSPACE_NOT_PUBLIC',

  FRIEND_TARGET_NOT_FOUND = 'FRIEND_TARGET_NOT_FOUND',
  FRIEND_CANNOT_SELF = 'FRIEND_CANNOT_SELF',
  FRIEND_ALREADY = 'FRIEND_ALREADY',
  FRIEND_BLOCKED = 'FRIEND_BLOCKED',
  FRIEND_REQUEST_DUPLICATE = 'FRIEND_REQUEST_DUPLICATE',
  FRIEND_NOT_FOUND = 'FRIEND_NOT_FOUND',
  FRIEND_INVALID_STATE = 'FRIEND_INVALID_STATE',
  FRIEND_CAP_REACHED = 'FRIEND_CAP_REACHED',

  // S16 (FR-DM-02): 그룹 DM 구성원 수 상한(본인 포함 ≤20) 초과. 요청 자체는
  // 형식상 유효하지만 도메인 한도를 넘어 처리 불가 → 422 (Unprocessable Entity).
  DM_GROUP_CAP_EXCEEDED = 'DM_GROUP_CAP_EXCEEDED',
  // S19 (FR-DM-12): 대상의 DM 수신권한(allowDmFrom=WORKSPACE_MEMBER)을 충족하지
  // 못해 DM 개시/멤버 추가가 거부됨(공통 워크스페이스 멤버도 ACCEPTED 친구도 아님).
  // 비노출 정책(H-03): friend-gate(FRIEND_NOT_FOUND) 와 동일한 중립 메시지를 쓰되
  // 권한 거부는 403 으로 분리해 클라이언트가 "DM 수신 차단됨" UI 로 분기할 수 있게 한다.
  DM_PRIVACY_RESTRICTED = 'DM_PRIVACY_RESTRICTED',

  INVITE_NOT_FOUND = 'INVITE_NOT_FOUND',
  INVITE_EXPIRED = 'INVITE_EXPIRED',
  INVITE_EXHAUSTED = 'INVITE_EXHAUSTED',
  INVITE_REVOKED = 'INVITE_REVOKED',
  BETA_INVITE_REQUIRED = 'BETA_INVITE_REQUIRED',

  CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
  CHANNEL_NAME_TAKEN = 'CHANNEL_NAME_TAKEN',
  CHANNEL_NAME_INVALID = 'CHANNEL_NAME_INVALID',
  CHANNEL_TYPE_NOT_IMPLEMENTED = 'CHANNEL_TYPE_NOT_IMPLEMENTED',
  CHANNEL_PURGED = 'CHANNEL_PURGED',
  CHANNEL_POSITION_INVALID = 'CHANNEL_POSITION_INVALID',
  CHANNEL_ARCHIVED = 'CHANNEL_ARCHIVED',
  // S13 (FR-CH-19): ANNOUNCEMENT 채널에서 게시 권한(SEND_MESSAGES /
  // WRITE_MESSAGE 비트) 없는 역할이 메시지를 POST → 403. 일반 권한 부족
  // (FORBIDDEN) 과 구분해 프론트가 "공지 채널 게시 제한" UI 를 띄울 수 있게 한다.
  CHANNEL_POSTING_RESTRICTED = 'CHANNEL_POSTING_RESTRICTED',
  // S14 (FR-CH-05): 비공개→공개 전환 시 confirmName(채널 이름) 누락/불일치.
  // 파괴적·되돌릴 수 없는 변경이므로 전용 코드로 분리해 클라이언트가
  // "이름 재입력" UI 를 띄울 수 있게 한다. → 400.
  CHANNEL_CONFIRM_REQUIRED = 'CHANNEL_CONFIRM_REQUIRED',
  // S14 (FR-CH-07): 비공개 채널은 초대 기반 가입만 허용 — 자유 가입 시도 거부. → 403.
  CHANNEL_PRIVATE_INVITE_ONLY = 'CHANNEL_PRIVATE_INVITE_ONLY',
  // S14 (FR-CH-07): 채널 멤버가 아닌데 탈퇴 시도. → 409.
  CHANNEL_NOT_MEMBER = 'CHANNEL_NOT_MEMBER',
  // S15 (FR-CH-08): 슬로우모드 활성 중 잔여 시간 내 재송신. → 429 + retry-after.
  // retryAfterMs(details) 로 잔여 밀리초를 실어보내 클라이언트가 카운트다운을
  // 띄울 수 있게 한다. BYPASS_SLOWMODE 비트 보유자는 이 게이트를 우회한다.
  CHANNEL_SLOWMODE_ACTIVE = 'CHANNEL_SLOWMODE_ACTIVE',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_TAKEN = 'CATEGORY_NAME_TAKEN',

  MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND',
  MESSAGE_CONTENT_INVALID = 'MESSAGE_CONTENT_INVALID',
  MESSAGE_CURSOR_INVALID = 'MESSAGE_CURSOR_INVALID',
  // S02 (FR-MSG-03 / FR-MSG-20): contentPlain 4,000자 초과.
  MESSAGE_TOO_LONG = 'MESSAGE_TOO_LONG',
  // S00 carryover (FR-MSG-23): mrkdwn 파서 ReDoS 방어 한도. 모두 400.
  // 한도는 shared-types MRKDWN_PARSE_LIMITS, throw 는 MrkdwnParseError.
  PARSE_TIMEOUT = 'PARSE_TIMEOUT',
  PARSE_DEPTH_EXCEEDED = 'PARSE_DEPTH_EXCEEDED',
  PARSE_NODE_LIMIT = 'PARSE_NODE_LIMIT',
  PARSE_AST_TOO_LARGE = 'PARSE_AST_TOO_LARGE',
  MESSAGE_NOT_AUTHOR = 'MESSAGE_NOT_AUTHOR',
  MESSAGE_THREAD_DEPTH_EXCEEDED = 'MESSAGE_THREAD_DEPTH_EXCEEDED',
  MESSAGE_PARENT_NOT_FOUND = 'MESSAGE_PARENT_NOT_FOUND',
  // task-044-iter2: pinned messages cap (50/channel, Discord parity).
  MESSAGE_PIN_CAP_EXCEEDED = 'MESSAGE_PIN_CAP_EXCEEDED',
  // S05 (FR-MSG-06): 편집 낙관적 잠금 충돌. expectedVersion ≠ 현재 version
  // → 409. 필터가 details.current(현재 MessageDto)를 응답 body 에 실어
  // 클라이언트가 편집창을 서버 최신값으로 롤백할 수 있게 합니다.
  MESSAGE_VERSION_CONFLICT = 'MESSAGE_VERSION_CONFLICT',
  IDEMPOTENCY_KEY_REUSE_CONFLICT = 'IDEMPOTENCY_KEY_REUSE_CONFLICT',

  // task-012-B attachments + task-012-D channel ACL
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_TOO_LARGE = 'ATTACHMENT_TOO_LARGE',
  ATTACHMENT_MIME_REJECTED = 'ATTACHMENT_MIME_REJECTED',
  ATTACHMENT_NOT_UPLOADED = 'ATTACHMENT_NOT_UPLOADED',
  ATTACHMENT_SIZE_MISMATCH = 'ATTACHMENT_SIZE_MISMATCH',
  CHANNEL_NOT_VISIBLE = 'CHANNEL_NOT_VISIBLE',

  // task-037-D custom emoji
  CUSTOM_EMOJI_NOT_FOUND = 'CUSTOM_EMOJI_NOT_FOUND',
  CUSTOM_EMOJI_NAME_TAKEN = 'CUSTOM_EMOJI_NAME_TAKEN',
  CUSTOM_EMOJI_NAME_INVALID = 'CUSTOM_EMOJI_NAME_INVALID',
  CUSTOM_EMOJI_CAP_REACHED = 'CUSTOM_EMOJI_CAP_REACHED',
  CUSTOM_EMOJI_MIME_REJECTED = 'CUSTOM_EMOJI_MIME_REJECTED',
  CUSTOM_EMOJI_TOO_LARGE = 'CUSTOM_EMOJI_TOO_LARGE',

  // task-038-B magic-byte mismatch between declared mime and actual
  // file prefix. 400 so the client surfaces it as a validation error
  // (not a content-type 415 — the client DID send a valid mime, it
  // just doesn't match what they actually uploaded).
  INVALID_MAGIC_BYTES = 'INVALID_MAGIC_BYTES',

  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL = 'INTERNAL',
}

export const ERROR_CODE_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_INVALID_TOKEN]: 401,
  [ErrorCode.AUTH_EMAIL_TAKEN]: 409,
  [ErrorCode.AUTH_USERNAME_TAKEN]: 409,
  [ErrorCode.AUTH_WEAK_PASSWORD]: 422,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 423,
  [ErrorCode.AUTH_SESSION_COMPROMISED]: 401,

  [ErrorCode.WORKSPACE_NOT_FOUND]: 404,
  [ErrorCode.WORKSPACE_NOT_MEMBER]: 404,
  [ErrorCode.WORKSPACE_SLUG_TAKEN]: 409,
  [ErrorCode.WORKSPACE_SLUG_RESERVED]: 422,
  [ErrorCode.WORKSPACE_INSUFFICIENT_ROLE]: 403,
  [ErrorCode.WORKSPACE_CANNOT_DEMOTE_OWNER]: 403,
  [ErrorCode.WORKSPACE_CANNOT_REMOVE_OWNER]: 403,
  [ErrorCode.WORKSPACE_OWNER_MUST_TRANSFER]: 409,
  [ErrorCode.WORKSPACE_TARGET_NOT_MEMBER]: 404,
  [ErrorCode.WORKSPACE_ALREADY_MEMBER]: 409,
  [ErrorCode.WORKSPACE_PURGED]: 410,
  [ErrorCode.WORKSPACE_NOT_PUBLIC]: 403,
  [ErrorCode.FRIEND_TARGET_NOT_FOUND]: 404,
  [ErrorCode.FRIEND_CANNOT_SELF]: 400,
  [ErrorCode.FRIEND_ALREADY]: 409,
  [ErrorCode.FRIEND_BLOCKED]: 403,
  [ErrorCode.FRIEND_REQUEST_DUPLICATE]: 409,
  [ErrorCode.FRIEND_NOT_FOUND]: 404,
  [ErrorCode.FRIEND_INVALID_STATE]: 409,
  [ErrorCode.FRIEND_CAP_REACHED]: 422,
  // S16 (FR-DM-02): 그룹 DM cap 초과 → 422.
  [ErrorCode.DM_GROUP_CAP_EXCEEDED]: 422,
  // S19 (FR-DM-12): DM 수신권한 미충족 → 403.
  [ErrorCode.DM_PRIVACY_RESTRICTED]: 403,

  [ErrorCode.INVITE_NOT_FOUND]: 404,
  [ErrorCode.INVITE_EXPIRED]: 410,
  [ErrorCode.INVITE_EXHAUSTED]: 410,
  [ErrorCode.INVITE_REVOKED]: 410,
  [ErrorCode.BETA_INVITE_REQUIRED]: 403,

  [ErrorCode.CHANNEL_NOT_FOUND]: 404,
  [ErrorCode.CHANNEL_NAME_TAKEN]: 409,
  [ErrorCode.CHANNEL_NAME_INVALID]: 422,
  [ErrorCode.CHANNEL_TYPE_NOT_IMPLEMENTED]: 422,
  [ErrorCode.CHANNEL_PURGED]: 410,
  [ErrorCode.CHANNEL_POSITION_INVALID]: 422,
  [ErrorCode.CHANNEL_ARCHIVED]: 409,
  // S13 (FR-CH-19): 공지 채널 게시 제한 → 403.
  [ErrorCode.CHANNEL_POSTING_RESTRICTED]: 403,
  // S14 (FR-CH-05): confirmName 누락/불일치는 400(검증 실패 계열).
  [ErrorCode.CHANNEL_CONFIRM_REQUIRED]: 400,
  // S14 (FR-CH-07): 비공개 채널 자유 가입 거부는 403.
  [ErrorCode.CHANNEL_PRIVATE_INVITE_ONLY]: 403,
  // S14 (FR-CH-07): 비멤버 탈퇴는 409(상태 충돌).
  [ErrorCode.CHANNEL_NOT_MEMBER]: 409,
  // S15 (FR-CH-08): 슬로우모드 활성은 429(rate-limit 계열) + retry-after.
  [ErrorCode.CHANNEL_SLOWMODE_ACTIVE]: 429,
  [ErrorCode.CATEGORY_NOT_FOUND]: 404,
  [ErrorCode.CATEGORY_NAME_TAKEN]: 409,

  [ErrorCode.MESSAGE_NOT_FOUND]: 404,
  [ErrorCode.MESSAGE_CONTENT_INVALID]: 422,
  [ErrorCode.MESSAGE_CURSOR_INVALID]: 400,
  // S02: 4,000자 초과는 400 (AC FR-MSG-03: "400 + MESSAGE_TOO_LONG").
  [ErrorCode.MESSAGE_TOO_LONG]: 400,
  // S00 carryover (FR-MSG-23): 파서 한도 위반은 모두 400.
  [ErrorCode.PARSE_TIMEOUT]: 400,
  [ErrorCode.PARSE_DEPTH_EXCEEDED]: 400,
  [ErrorCode.PARSE_NODE_LIMIT]: 400,
  [ErrorCode.PARSE_AST_TOO_LARGE]: 400,
  [ErrorCode.MESSAGE_NOT_AUTHOR]: 403,
  [ErrorCode.MESSAGE_THREAD_DEPTH_EXCEEDED]: 400,
  [ErrorCode.MESSAGE_PARENT_NOT_FOUND]: 404,
  [ErrorCode.MESSAGE_PIN_CAP_EXCEEDED]: 422,
  // S05 (FR-MSG-06): 낙관적 잠금 충돌은 409 (IDEMPOTENCY_KEY_REUSE_CONFLICT 와 동일 매핑).
  [ErrorCode.MESSAGE_VERSION_CONFLICT]: 409,
  [ErrorCode.IDEMPOTENCY_KEY_REUSE_CONFLICT]: 409,

  [ErrorCode.ATTACHMENT_NOT_FOUND]: 404,
  [ErrorCode.ATTACHMENT_TOO_LARGE]: 413,
  [ErrorCode.ATTACHMENT_MIME_REJECTED]: 415,
  [ErrorCode.ATTACHMENT_NOT_UPLOADED]: 409,
  [ErrorCode.ATTACHMENT_SIZE_MISMATCH]: 409,
  [ErrorCode.CHANNEL_NOT_VISIBLE]: 403,

  [ErrorCode.CUSTOM_EMOJI_NOT_FOUND]: 404,
  [ErrorCode.CUSTOM_EMOJI_NAME_TAKEN]: 409,
  [ErrorCode.CUSTOM_EMOJI_NAME_INVALID]: 422,
  [ErrorCode.CUSTOM_EMOJI_CAP_REACHED]: 422,
  [ErrorCode.CUSTOM_EMOJI_MIME_REJECTED]: 415,
  [ErrorCode.CUSTOM_EMOJI_TOO_LARGE]: 413,
  // task-039-D: 422 (Unprocessable Entity) is more accurate than 400
  // — the request envelope is well-formed JSON with valid fields, but
  // the uploaded payload's magic bytes do not match the declared
  // mime, so the server cannot process it. 400 was reserved for
  // shape errors (parse failures / missing required fields).
  [ErrorCode.INVALID_MAGIC_BYTES]: 422,

  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.INTERNAL]: 500,
};
